#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [ "${BRANCH_NAME}" == "master" ] && git diff --staged package.json | grep -q "eslint"; then
    echo ">>> run ci"
    exit 0
fi

COMMIT_MSG_FILE=$1
echo "[skip ci]" >> $COMMIT_MSG_FILE
echo ">>> skip ci"