name: sub1
on:
  push:
    branches:
      - master
    paths:
      - "apps/sub1/**"
jobs:
  test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: apps/sub1
    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "NOW=$(TZ=Asia/Seoul date '+%y-%m-%d')" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: test-image/url-pay
          tags: type=sha,prefix=url-pay-${NOW}-

      - name: Echo tag
        run: |
          echo $NOW
          echo ${{ steps.meta.outputs.tags }}

      - name: shell script copy
        run: |
          chmod +x ./copy.sh
          ./copy.sh

      # - name: Build Docker image
      #   run: docker build -t test-image:latest apps/sub1

      # - name: Install Dependencies
      #   run: yarn install --immutable

      # - name: Run Action Script
      #   run: yarn action

      # - name: Print list
      #   run: ls -al
