name: sub1
on:
  push:
    branches:
      - master
    paths:
      - "packages/sub1/**"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sub1
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/sub1
