name: sub1 asdfas
on:
  push:
    branches: [master, release]
    # paths-ignore:
    #   - apps/sub2/**
    #   - apps/sub3/**

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files in the docs folder
        id: changed
        uses: tj-actions/changed-files@v38
        with:
          files_yaml: |
            sub1:
              - "!apps/sub2/**"
              - "!apps/sub3/**"
            sub2:
              - "!apps/sub1/**"
              - "!apps/sub3/**"

      - name: changed console
        run: |
          echo "changed: ${{ steps.changed.outputs.sub1_any_changed }}"
          echo "changed: ${{ steps.changed.outputs.sub2_any_changed }}"
          for key in ${{ steps.changed.outputs }}; do
            # echo "Key: $key, Value: ${steps.changed.outputs[$key]}"
            echo "Key: $key"
          done