name: sub1 asdfas
on:
  push:
    branches: [master, release]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: test
        run: |
          git log --oneline