name: sub1 asdfas
on:
  push:
    branches: [master, release]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo github run_number
        run: echo ${{ github.run_number }}
    outputs:
      changed: ${{ env.CHANGED }}
