name: Github-Action-Test
on:
  push:
    branches:
      - master
    paths:
      - "packages/sub1/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run Action Script
        run: yarn sub1 run action
