name: sub1
on:
  push:
    branches: [master, release]
    paths:
      - .github/workflows/sub1.yml
      - apps/sub1/**

jobs:
  job1:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: apps/sub1
    steps:
      - name: test
        run: ls -alh /home/runner/work

  #     - name: Set env for master branch
  #       if: github.ref == 'refs/heads/master'
  #       run: echo "ENABLE_DEPLOY=false" >> $GITHUB_ENV

  #     - uses: actions/checkout@v3

  #     - name: Set current date as env variable
  #       run: echo "NOW=$(TZ=Asia/Seoul date '+%y-%m-%d')" >> $GITHUB_ENV

  #     - name: Echo tag
  #       run: |
  #         echo $NOW
  #         echo ${{ steps.meta.outputs.tags }}
  #         echo ${{ steps.meta.outputs.version }}

  #     - name: Sleep for 30 seconds
  #       uses: jakejarvis/wait-action@master
  #       with:
  #         time: "30s"

  #   outputs:
  #     enable_deploy: ${{ env.ENABLE_DEPLOY }}

  # job2:
  #   if: ${{ needs.job1.outputs.enable_deploy == 'true' }}
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Print job1 version
  #       run: echo ${{ needs.test1.outputs.version }}
