name: sub1 asdfas
on:
  push:
    branches: [master, release]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Changed Files
        id: filter
        uses: tj-actions/changed-files@v38
        with:
          files_yaml_from_source_file: ".github/filter.yml"
      
      - name: Set Changed Files Env
        run: |
          if [ ${{ steps.filter.outputs.sub1_any_changed }} == "true" ]; then
            echo "CHANGED=sub1" >> $GITHUB_ENV
          elif [ ${{ steps.filter.outputs.sub2_any_changed }} == "true" ]; then
            echo "CHANGED=sub2" >> $GITHUB_ENV
          fi

      - name: changed console
        run: |
          echo "changed: ${{ env.CHANGED }}"
    outputs:
      changed: ${{ env.CHANGED }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job2 console
        run: |
          echo "changed: ${{ needs.job1.outputs.changed }}"
