name: sub1 asdfas
on:
  push:
    branches: [master, release]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Changed Files
        id: filter
        uses: tj-actions/changed-files@v38
        with:
          files_yaml_from_source_file: ".github/filter.yml"

      - name: Set Changed Files Env
        run: |
          ALL_SERVERS=("sub1", "sub2")
          for server in "${ALL_SERVERS[@]}"; do
            if [ $(echo "steps.filter.outputs.${server}_any_changed") == 'true' ]; then
              CHANGED="${CHANGED} ${server}"
            fi
          done
          echo "CHANGED=${CHANGED}" >> $GITHUB_ENV

      - name: console
        run: |
          for c in ${{ env.CHANGED }}; do
            echo "changed: $c"
          done
    outputs:
      changed: ${{ env.CHANGED }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job2 console
        run: |
          echo "changed: ${{ needs.job1.outputs.changed }}"
