name: sub1
on:
  push:
    branches:
      - master
    paths:
      - "packages/sub1/**"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sub1
    steps:
      - uses: actions/checkout@v3

      - name: Print list
        run: echo "ls -al"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Action Script
        run: yarn action
