name: sub1
on:
  push:
    branches:
      - master
    paths:
      - "apps/sub1/**"

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Set current date as env variable
      #   run: echo "NOW=$(TZ=Asia/Seoul date '+%y-%m-%d')" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: test-image/url-pay
          tags: type=sha,prefix=url-pay-${{ env.NOW }}-

      - name: Echo tag
        run: |
          echo $NOW
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: apps/sub1/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Echo tag
        run: |
          echo $NOW
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.version }}
