name: sub1
on:
  push:
    branches:
      - master
    paths:
      - "packages/sub1/**"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sub1
    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: apps/sub1/Dockerfile
          push: false

      # - name: Install Dependencies
      #   run: yarn install --immutable

      # - name: Run Action Script
      #   run: yarn action

      # - name: Print list
      #   run: ls -al
