name: sub2
on:
  push:
    branches: [master, release]
    paths:
      - .github/workflows/sub2.yml
      - apps/sub2/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set build env and version
        run: |
          echo "DIRECTORY=develop/" >> $GITHUB_ENV && echo "BUILD_ENV=develop" >> $GITHUB_ENV

      - name: Print
        run: |
          echo "$GITHUB_ENV"
          echo "directory: ${DIRECTORY}"
          echo "build_env: ${BUILD_ENV}"

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"
