name: sub2
on:
  push:
    branches:
      - master
    paths:
      - "packages/sub2/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set build env and version
        run: |
          echo "BUILD_ENV=production; VERSION=$(echo $GITHUB_REF | cut -d'/' -f 4)-${GITHUB_SHA::6}" >> $GITHUB_ENV
          echo "$GITHUB_REF_NAME, $GITHUB_SHA ${GITHUB_SHA::6}, $GITHUB_ENV"

      - name: Print
        run: |
          echo "$GITHUB_ENV"

      # - name: Install Dependencies
      #   run: yarn install --immutable

      # - name: Run Action Script
      #   run: yarn sub1 run action
